/**
 * Regression test: API JSON updated_at timestamps
 *
 * Validates that public/api/appointments.json and public/api/wellness.json
 * contain correctly-formatted timestamp fields that are updated whenever
 * the dashboard-refresh skill regenerates the API data.
 *
 * Fields under test:
 *   appointments.json  →  updated_at        (top-level)
 *   wellness.json      →  meta.generated_at  (generation timestamp)
 *   wellness.json      →  summary.last_updated (last-updated echo)
 */

const fs = require('fs');
const path = require('path');

const API_DIR = path.resolve(__dirname, '../../public/api');

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

/** Return parsed JSON for a file inside public/api/ */
function loadApiJson(filename) {
  const filePath = path.join(API_DIR, filename);
  const raw = fs.readFileSync(filePath, 'utf-8');
  return JSON.parse(raw);
}

/**
 * ISO-8601 datetime regex (with or without trailing Z / offset / microseconds).
 * Accepts formats produced by the vault generator:
 *   2026-04-14T19:32:32Z
 *   2026-04-14T19:32:32.000000
 *   2026-04-14T19:32:32+00:00
 */
const ISO_DATE_RE =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?$/;

/** Assert a string is a parseable ISO-8601 datetime */
function expectValidIsoDate(value, label) {
  expect(typeof value).toBe('string');
  expect(value).toMatch(ISO_DATE_RE);
  const parsed = new Date(value);
  expect(parsed.toString()).not.toBe('Invalid Date');
  // Sanity: timestamp should be after the project start (surgery date Oct 2024)
  expect(parsed.getTime()).toBeGreaterThan(new Date('2024-10-01').getTime());
  return parsed;
}

/* ------------------------------------------------------------------ */
/*  Tests                                                              */
/* ------------------------------------------------------------------ */

describe('appointments.json updated_at', () => {
  let data;

  beforeAll(() => {
    data = loadApiJson('appointments.json');
  });

  test('file loads as valid JSON with expected top-level keys', () => {
    expect(data).toBeDefined();
    expect(data).toHaveProperty('updated_at');
    expect(data).toHaveProperty('appointments');
    expect(Array.isArray(data.appointments)).toBe(true);
  });

  test('updated_at is a valid ISO-8601 datetime', () => {
    expectValidIsoDate(data.updated_at, 'appointments.updated_at');
  });

  test('updated_at is not in the future', () => {
    const ts = new Date(data.updated_at);
    // Allow a small buffer (1 day) for timezone differences
    const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000);
    expect(ts.getTime()).toBeLessThanOrEqual(tomorrow.getTime());
  });
});

describe('wellness.json updated_at / generated_at', () => {
  let data;

  beforeAll(() => {
    data = loadApiJson('wellness.json');
  });

  test('file loads as valid JSON with expected structure', () => {
    expect(data).toBeDefined();
    expect(data).toHaveProperty('meta');
    expect(data).toHaveProperty('summary');
  });

  test('meta.generated_at is a valid ISO-8601 datetime', () => {
    expect(data.meta).toHaveProperty('generated_at');
    expectValidIsoDate(data.meta.generated_at, 'wellness.meta.generated_at');
  });

  test('summary.last_updated is a valid ISO-8601 datetime', () => {
    expect(data.summary).toHaveProperty('last_updated');
    expectValidIsoDate(data.summary.last_updated, 'wellness.summary.last_updated');
  });

  test('meta.generated_at and summary.last_updated are consistent', () => {
    const generatedAt = new Date(data.meta.generated_at);
    const lastUpdated = new Date(data.summary.last_updated);
    // They should be the same timestamp (both set during the same refresh)
    const diffMs = Math.abs(generatedAt.getTime() - lastUpdated.getTime());
    // Allow up to 1 second of drift in case of rounding
    expect(diffMs).toBeLessThanOrEqual(1000);
  });

  test('generated_at is not in the future', () => {
    const ts = new Date(data.meta.generated_at);
    const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000);
    expect(ts.getTime()).toBeLessThanOrEqual(tomorrow.getTime());
  });
});

describe('cross-file timestamp consistency', () => {
  let appointments;
  let wellness;

  beforeAll(() => {
    appointments = loadApiJson('appointments.json');
    wellness = loadApiJson('wellness.json');
  });

  test('appointments.updated_at and wellness.meta.generated_at come from the same refresh', () => {
    const apptTs = new Date(appointments.updated_at);
    const wellTs = new Date(wellness.meta.generated_at);

    // Both files are generated by the same refresh script, so their
    // timestamps should be within a small window of each other.
    const diffMs = Math.abs(apptTs.getTime() - wellTs.getTime());
    // Allow up to 60 seconds — the generator writes them sequentially
    expect(diffMs).toBeLessThanOrEqual(60 * 1000);
  });

  test('both timestamps are from the same calendar day (UTC)', () => {
    const apptDate = new Date(appointments.updated_at).toISOString().slice(0, 10);
    const wellDate = new Date(wellness.meta.generated_at).toISOString().slice(0, 10);
    expect(apptDate).toBe(wellDate);
  });
});
